### ISSUE TITLE
Fork and edit

### ISSUE THREAD

**Issue by MarcoKuehne** [PMassicotte/ivado_ggplot2_workshop_2022#1]
Hi Philippe, awesome data viz presentation. Some links are broken like https://pmassicotte.github.io/ivado_ggplot2_workshop_2022/#16 I forked the repo and was trying to knit the presentation myself, in addition to some of your personal packages like `ggmpthemes` I experience a problem with an `html_dependency`  "/home/pmassicotte/R/x86_64-pc-linux-gnu-library/4.1/kableExtra/kePrint-0.0.1" Can you give me a hint how to solve this error?

**Comment by PMassicotte** [comment]
Hi @MarcoKuehne.

1. Can you try to run `renv::repari()` and/or `renv::rebuilt()`? 
2. You can also set `cache = FALSE` to force rebuilding the cache.

Let me know how it works.

**Comment by MarcoKuehne** [comment]
Hi, thanks for quick response. Cache solved the problem.
